server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
      routes:
        - id: comment
          uri: lb://COMMENT
          predicates:
            - Path=/api/v1/comments/**
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/users/**
        - id: post
          uri: lb://POST
          predicates:
            - Path=/api/v1/posts/**
